name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build App Docker Image
      run: docker build -t aelshemy/docker-react -f Dockerfile.dev
      
    - name: Run Test Cases
      run: docker run -e CI=true aelshemy/docker-react npm run test -- --coverage
